export const defaultCustomization = {
  id: 0,
  selectedTheme: 1,
  selectedBgColor: "#fff",
  selectedHeader: "logo-header",
  selectedLayout: "theme-grid",
  selectedPrimaryColor: "#28509E",
  selectedSecondaryColor: "#6b7280",
  selectedTextColor: "#000",
  selectedIconColor: "#ffffff",
  resto_id: 0,
  created_at: "",
  updated_at: "",
  resto: {
    id: 0,
    name: "",
    slug: "",
    user_id: 0,
    created_at: "",
    updated_at: "",
    visitor_count: 0,
    daily_visitor_counts: {},
    active_resto: 0,
  },
};
